### ISSUE TITLE
Error When Streaming

### ISSUE THREAD

**Issue by HaleyMueller** [brodokk/jellyfin2txt#10] opened 2024-08-14 17:20 UTC
Error when trying to stream:

```
MediaBrowser.Common.Extensions.ResourceNotFoundException: Session f83a19717b6bf21006f6efd1e99178f0 not found.
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
```

Do I also need to fill out Subtitle proxy url?

**Comment by brodokk** [comment] 2024-08-15 00:58
Hey! I do not run this service on my server for some month already and it's possible their is some change since then with the API of Jellyfin.

But to respond to the question, no you should not have too.

Based on the error message this sounds like an auth issue when talking with your Jellyfin server.

I could see tomorrow if i have time to start this service again and see if i can reproduce this.

**Comment by brodokk** [comment] 2024-08-15 10:33
After a quick test everything still work with the version `10.8.8` but this is not the up to date version. I will update my Jellyfin server and try again!

What is your version of Jellyfin? What is the command you are trying to use when requesting jellyfin2txt?

**Comment by brodokk** [comment] 2024-08-15 10:45
OK even with the version `10.9.9` I don't have this problem. I will need more information.

**Comment by HaleyMueller** [comment] 2024-08-16 00:43
Does this need to be a public server or can I just run it locally?

**Comment by brodokk** [comment] 2024-08-16 12:31
I did only test on a public accessible server but I do not see any reason why it would not work on a local server. I suppose by local it mean access via 121.0.0.1 or an ip like 192.168.x.x. I could try that too.

**Comment by HaleyMueller** [comment] 2024-08-17 00:24
I found out the issue. In the config I had a slash at the end of the url:

`https://URL.com/`

Removing the slash fixed it

**Comment by brodokk** [comment] 2024-08-17 23:27
Interesting I can't reproduce still... I don't like that tho and I would like to being able to fix that. Which endpoint did you try to hit on the proxy?

**Comment by HaleyMueller** [comment] 2024-08-18 19:32
Server URL having the string transfer's over to your current in game jellyfin media view:
![image](https://github.com/user-attachments/assets/c4c228c0-a499-49e3-965a-1c5218fe6509)


![image](https://github.com/user-attachments/assets/79d1c1b9-ae09-48de-ac5a-c512a93cb8a3)

Same thing for the thumbnail images too: 
![image](https://github.com/user-attachments/assets/28fb818a-69a7-40d4-931c-a9459819e979)

There is also some leaked jellyfin urls that get in the resonite log file too:

![image](https://github.com/user-attachments/assets/7a982687-bc26-42b9-9f53-6c3ea6ebc8f5)

**Comment by brodokk** [comment] 2024-08-19 01:21
Ok for the SERVER_URL this should be fixed in the commit https://github.com/brodokk/jellyfin2txt/commit/518a31660b8521ee315e4f1c3ba3478bc04bd5f9

The build of the docker image is not working for now, i'm looking on that. FIXED!

And good catch for the leak! It's from the demo client on resonite, new version shipped who don't have that.

I'm closing the issue for now, thks again for your report!

**Closed as completed by brodokk** 2024-08-19 01:21 UTC
